version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/jason/github/nginx-proxy/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

networks:
  default:
    name: nginx_default
    external: true