version: '2'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:1.4
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - /Users/jason/Github/nginx-proxy/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro # optional custom config file

networks:
  default:
    name: nginx-default
    external: true
